apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://radarinen1bprometheus.herokuapp.com
    basicAuth: false
    isDefault: true
    editable: true