[[section-introduction-and-goals]]
[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****
== Introduction and Goals

Radarin is a system that facilitates meetings between friends using new technologies. The application can get access to the mobile phone location of users who voluntarily activate it, and allow other users who are their friends to know when they are near them.

The application allows the user to be notified when there is a friend nearby, so they can get in contact.

The system is compatible with https://solidproject.org/[Solid Project], and it securely stores data in decentralized data stores called Pods. Moreover, the system will ask for permission to access the information of the corresponding user's pods.

The system can only store locations and timestamps in which these events take place. It will avoid storing any other type of personal information about the users.


[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Requirements Overview
The requirements where provided to us https://arquisoft.github.io/course2021/labAssignmentDescription.html#requirements[here].

Two Software components have to be taken into account:

    . A Web application running on a server.

    Stores all data received from the application (stored in Pods). 
    Minimum amount of information has to be stored.
    Is the one charge of storing, managing and visualizing locations among other administration options (such as monitor the status of the server). 

    . An application running on the user's phone.
    
    Sending the location to the server and receiving the location of nearby friends (only with the user's consent).

Tools used for system deployment are https://www.docker.com/[docker] (containers) and https://heroku.com/[heroku] (cloud service).

Unit, acceptance and load tests have to be designed and written to be run automatically in a continuous integration server.

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
=== Quality Goals
Top 3 Quality goals for the application:

.Security
Having completely safe and confidential relation between the server and the phone application, where minimum information is asked for.
Where only the users can access that data, or if allowed, friends can also see it.

.Performance/Efficiency
Fast and responsive times when accessing information and features.
With timming close to the following:
- Under 4 seconds for logging in.
- Sending the current location and receiving other friends locations every 15-20 seconds (more or less time can maybe be setup using the app, so users can choose between using a more or less resource consuming approach, and thus adding more flexibility)
- Sending information such as reviews / pictures in 5 seconds or less.

.Usability
Having an easy to learn, easy to use application which anyone can install and run with close to no doubts or problems.

Other important quality goals are:

.Reliability
Having an application that is reliable, available at all times, being tolerant with possible errors occuring and being able to recover from these errors.

.Compatibility
Different versions for different operating systems, so users with all types of phones can experience the application. 

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
=== Stakeholders



[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Providers_ | _Suppliers and Vendors_ | _A working, secure, efficient architecture and design for the application_
| _Influencers_ | _Trade unions / Lobby groups_ | _A product which is attractive and modern_
| _Governance_ | _Auditors, regulators, and health and safety executives_ | _Final safe and good quality project_
| _End users_ | _People that will use the application on a daily basis_ | _Efficient, reliable and secure application_
|===
