[[section-introduction-and-goals]]
[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****
== Introduction and Goals

Radarin is a system that facilitates meetings between friends using new technologies. The application can get access to the mobile phone location of users who voluntarily activate it, and allow other users who are their friends to know when they are near them.

The application allows the user to be notified when there is a friend nearby, so they can get in contact.

The system is compatible with https://solidproject.org/[Solid Project], and it securely stores data in decentralized data stores called Pods. Moreover, the system will ask for permission to access the information of the corresponding user's pods.

The system can only store locations and timestamps in which these events take place. It will avoid storing any other type of personal information about the users.

The deployment is done https://radarinen1bwebapp.herokuapp.com/[here].

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Requirements Overview
The requirements where provided to us https://arquisoft.github.io/course2021/labAssignmentDescription.html#requirements[here].
|===
|Functional requirements |Implementation requirements

|To store, manage and visualize locations among other administration options.
|A Web application that will run in a server.

|Send locations and receive notifications from nearby users.
|An application that will run in user's mobile phone.

|Store the minimum needed information of a user.
|The database will only store a reference to the users pods and the last location of each user

|Keep the locations of the user secured.
|The pods will contain all the locations the user will upload themselves, only obtainable by them and the people they give access tp.

|Deploy the system.
|The deployment will work from docker containers and from a cloud service like heroku.

|Monitor the system.
|Option included in the Web application, allowing also to monitor the server status.

|Test that the system works properly.
|Unitary tests and load tests running in a continuous integration server.
|===
[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
=== Quality Goals
Top 3 Quality goals for the application:

.Security
Having completely safe and confidential relation between the server and the phone application, where minimum information is asked for.
Where only the users can access that data, or if allowed, friends can also see it.

.Performance/Efficiency
Fast and responsive times when accessing information and features.
With timming close to the following:
- Under 4 seconds for logging in.
- Sending the current location and receiving other friends locations every 25 seconds (Enough time for the map to be completely refreshed with noticable changes and for the application to not overcharge the database)

.Usability
Having an easy to learn, easy to use application which anyone can run with close to no doubts or problems, using similar components to the ones that appear in webs that work the same way.

Other important quality goals are:

.Reliability
Having an application that is reliable, available at all times, being tolerant with possible errors occuring and being able to recover from these errors.

.Compatibility
Since both applications are based on web, they will function in every system that has access to the web via web browser. The browser will ask for permissions when connecting to the app. 

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
=== Stakeholders

==== Enterprise view

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Providers_ | _Suppliers and Vendors_ | _A working, secure, efficient architecture and design for the application_
| _Influencers_ | _Trade unions / Lobby groups_ | _A product which is attractive and modern_
| _Governance_ | _Auditors, regulators, and health and safety executives_ | _Final safe and good quality project_
| _End users_ | _People that will use the application on a daily basis_ | _Efficient, reliable and secure application_
|===

==== Educational view

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Teachers_ | _Both the people that assigned the task to the developers and the ones that will evaluate both the procedure and result of such assignment_ | _A functional system that will be compatible with the SOLID project, storing information in pods (evaulating the security), which corresponds to the assignement given and that is easy to use, responsive and original_
| _Developers_ | _The people who will work on the systems and make decisions to determine the design and architecture of the application_ | _A complete system who fulfills all the requirements given to them_
| _Users_ | _The posible users the system may have in a future_ | _A system that will provide the functionality that it offers, with the security that it is promised and which is easy to use and a good option for a long-term use_
| _Specialized developers (for example Empathy workers)_ | _People that are very experienced in the architectures and functionalities we are going to develop_ | _A system that follows the guidelines specified by the software we are using and that follows all the expected conventions_
|===
