[[section-system-scope-and-context]]
== System Scope and Context 
This chapter describes the environment and context of _radarin_: Who uses the system and on which other system does _radarin_ depend +

=== Business Context
In the business context of Radarin we can distinguish three parts. 
These are:

* Application server 
* User's POD 
* User 

The basic interactions of these parts can be observed in the following diagram
----
:User1: --> [User1's Pod]: interacts
[User1's Pod] --> [Main App]: Send location
[Main App] --> [User1's Pod]: Manages
:User2: --> [User2's Pod]: interacts
[User2's Pod] - [User1's Pod]: send notifications
[User2's Pod] --> [Main App]: Send location
[Main App] --> [User2's Pod]: Manages
----

In the following table, we will explain the roles, and the actions they perform, explained in the
previous diagram.

[options="header",cols="1,2"]
|===
|Role/Name|Description
| Main App | Main app manages every user's pod, it doesn't access user data until it gets the permission to do that, such that information of the friends of the user, its location... It helps user to interact between them 
| Users | Users will use the application to share and interact with another users, by interacting with their respective pods.
| User pods | Bridge between the Main App and the users. Users interact with them, and after permission by the user, it exchanges information with the Main App, for instance, the location of the user. It is managed by the Main App.
|===

