[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions
_radarin_ is an application built mainly in JavaScript that wants to be user friendly when managing the information, that's why it uses *SOLID*, which is basically a technology that allows the users to store their data on a Solid POD, where they have full control over it, managing which slices of the POD are shared with those who access it.

In terms of functionality, _radarin_ uses *Docker* and *React* as tools for working with the software.
*Docker* is a software platform which packs software in standarized units called containers, which include everything necessary for the sofware to be executed. This means that Docker allows combining application source code with all the operating system libraries and dependencies required to run the code in any environment.
*React* is a JavaScript library to build user interfaces. It is based on isolated components that manage their own state, allowing to build powerful and complex user interfaces in an easy way.

The database that we manage within the application is a NoSQL database, specifically, a *MongoDB* database. This will ease communication with data since the transactions with the database will be via aggregates, which are organized in a JSON (JavaScript Object Notation) structure, simplifying a lot their management in JavaScript.

Some of these technology decisions that we took make a huge impact on quality. For example, by working with *React* we can ensure complex and functional user interfaces, by using *Docker* we free the user from compatibility or dependency issues when running the app, and by using *SOLID* technology we allow the users to have control over their privacy.

To meet every possible quality goal, in _radarin_ we perform extensive test operations.

In terms of organization to work in the project, since the working team is huge, we divide the huge workload in different, single parts, that can be completed by a group of one or two people. Our approach to put it all together is using GitHub. Vía pull request and heavy communication and collaboration, we can discuss problems, review things, and ensure that everything is correct before integrating it with the stable branches.

[role="arc42help"]
****

.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
