[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions
_radarin_ is an application built mainly in JavaScript that strives to be user friendly when managing the information, that's why it uses *SOLID*, which is a web decentralization project that allows the users to store their data in a Solid POD, where they have full control over it, managing which slices of the POD are shared with those who access it.

In terms of functionality, _radarin_ uses *Docker* and *React* as tools for working with the software.
*Docker* is a software platform which packs software in standarized units called containers, which includes everything necessary for the software to be executed. This means that Docker allows combining application source code with all the operating system libraries and dependencies required to run the code in any environment.
*React* is a JavaScript library to build user interfaces. It is based on isolated components that manage their own state, allowing to build powerful and complex user interfaces in an easy way.

The database that we manage within the application is a NoSQL database, specifically, a *MongoDB* database. This will ease communication with data since the transactions with the database will be via aggregates, which are organized in a JSON (JavaScript Object Notation) structure, simplifying a lot their management in JavaScript.

Some of these technology decisions that we took make a huge impact on quality. For example, by working with *React* we can ensure complex and functional user interfaces, by using *Docker* we free the user from compatibility or dependency issues when running the app, and by using *SOLID* technology we allow the users to have control over their privacy.

=== Decisions about the top-level decomposition of the system
The architectural pattern that we will be using in our project is a slight modification of a *Client-Server* pattern. In this variation, we have a client which requests from many servers that are managed by different users (the User PODs). They are decentralized databases that the client is going to query and manage.

=== Quality goals
We aim to obtain several quality goals in radarin:
[options="header",cols="1,2"]
|===
|Quality goal|Description
| User data-friendly | One of the main goals of the application is to be friendly in terms of user information management. That's why we use SOLID technology, allowing users to be the absolute owners of their own data.
| Non-frustrating | As we are developing an application that bases on user interaction, one of our main goals is to lower as much as possible the latency
or lag between operations to keep the users waiting as less as possible.
| Tested | Our application must behave correctly under different scenarios. That's why we perform extensive testing to check that everything works fine.
|===

=== Organizational decisions
In terms of organization to work in the project, since the working team is huge, we divide the huge workload in different, single parts, that can be completed by a group of one or two people. Our approach to put it all together is using GitHub. Vía pull request and heavy communication and collaboration, we can discuss problems, review things, and ensure that everything is correct before integrating it with the stable branches.
