[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
This section will be in contrast with the last, as we will cover here the dynamic behaviour and how users interact between them.

=== Alice wants to know if his friends are near her. (First execution)


* _Today, Alice is bored at home, but she wants to do something, taking into account COVID-19 restrictions.
    As a consequence of these restrictions, she cannot leave her town, and wants to know if some of his friends are near her._
* _As you can see in the diagram below, at first Alice has to authenticate and allow sharing his location in order to find his mutuals between a proximity radius.
    Once this is done, the mobile application will ask Alice of she wants to share her location with her mutuals. In this case, she wants, and as a result, her location will be stored in the database as the last location (in the database only the last location of a user with its timestamp is stored), and the app will query the database to get those friends that are near her (the necessary conditions for a person to be near of other are: having updated the location at least 15 minutes from the request time, and being in a radius of one kilometer). After this, the database will retrieve the users near Alice, showing a notification in the screen, and adding several markers in the map. (This process will be repeated every 10 seconds, even if the user has the web in background)_

[plantuml,"Sequence diagram 1",png]
----
actor Alice
entity MAApp as "Alice's Mobile App"
database Pod1 as "Alice's Pod"
database Server as "Main Database"
Alice --> MAApp: Authenticates and allows to share her location
MAApp --> Pod1: Accesses the list of friends
MAApp --> Server: Sends to the database the list of friends
MAApp --> Server: Sends the last location
Server <-- Server: Manages distances and times
MAApp <-- Server: Retrieves locations of the friends
Alice <-- MAApp: The radar is shown
----

=== Alice wants to know if his friends are near her. (Following executions)
* _In this case, we have the same exact context as in the previous use case, but this time, as Alice has introduced her crendentials previously, some steps will be skipped._
* _It is the same context. Alice was already authenticated, and allowed to share her location, but this time, the mobile app will send directly her location to the database._

[plantuml,"Sequence diagram 2",png]
----
actor Alice
entity MAApp as "Alice's Mobile App"
database Pod1 as "Alice's Pod"
database Server as "Main Database"
MAApp --> Server: Sends to the database the list of friends
MAApp --> Server: Sends the last location
Server <-- Server: Manages distances and times
MAApp <-- Server: Retrieves locations of the friends
Alice <-- MAApp: The radar is shown
----

=== Alice wants to know if his friends are near her, but she doesn't have Internet Connection.
* _In this case, we have the same exact context as in the previous use case, but this time, Alice went for a walk with her dog to the mountain, and at a certain point of the walk, she lost the connection to the Internet._
* _It is the same context. Alice was already authenticated, and allowed to share her location, but with after some time, the server has not received any recent location (more recent than a given amount of time), and, as a consequence, she is not able to see the radar._

[plantuml,"Sequence diagram 3",png]
----
actor Alice
entity MAApp as "Alice's Mobile App"
database Pod1 as "Alice's Pod"
database Server as "Web Server"
Alice --> MAApp: Authenticates and allows to share her location
MAApp --> Pod1: Accesses the list of friends
MAApp --> Server: Is not able to send the location
MAApp <-- Pod1: No new information is retrieved
MAApp <-- MAApp: It is not able to compute what is needed
Alice <-- MAApp: An alert is shown
----


