[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****


.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

[plantuml,"Component diagram",png]
----
node "<<device>>\nWindows-PC" {
     
    component [Browser] as NavegadorPc
    
 }
node "MongoDB Atlas" as mongo {
    database "MainApp.db" as MainDatabase
}

node "<<device>>\n POD Provider" as podProvider {
 
 database "user POD" as upod
}

node "Heroku server" as MainPage{
   component "Radarin Manager (Web-intended version)" as MainApp {
       component [App.js] as MainIndex
    }   
   component "Radarin Radar (Mobile-intended version)" as MobileApp {
        component [App.js] as MobileIndex
   }
}

node "<<device>>\nMobile Phone" as Mobile {

  component [Browser] as NavegadorMovil
}

NavegadorPc --> MainIndex
NavegadorMovil --> MobileIndex

MainApp --> mongo
MainApp --> podProvider
MobileApp --> podProvider

----

Motivation::

_The principal motivation for choosing this structure, was to make the application decentralized. We want to store the minimum data needed of the users in our databases. Of course we will ask users for information, but they decide what to share._

Quality and/or Performance Features::

_Regarding performance terms, our software will work very fluent, as the majority of the data will be stored in the user's devices, not needing to access the server database except for excepcional situations, where some information will be asked to the users to be shared, but that will not be stored in the database._

Mapping of Building Blocks to Infrastructure::
_Mobile phone and Windows devices will be the user's devices that will access the Application, passing through our server, where the application is deployed. Then, some data will be read from our database, and some other will be asked to the user to be shared and processed by the app, but not stored in our registries._


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****


