[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.
****

@startmindmap
* Efficiency
    * One of the highest priority qualities
    * Fast comunications between the mobile and the web applications 
* Security
    * #1 Quality
    * Information stored in pods
* Testability
    * Integrated server dedicated for tests
* Usability
    * Easy and simple to use user interface
* Reliability 
    * Integration to receive notifications between the different users' device 
@endmindmap

=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****

==== Usage Scenarios
* The aplication will be testeable since using the React framework allowa us to find bugs and possible errors easily, as tests will be run in a continuos integration server.
* The application is responsive: The Web application will record the locations as the user will register them, and the mobile application will receive notifications from nearby users as soon as the devices can (for example, the mobile application will send the location every 
15 seconds, so that it is reponsive and at the same time it doesnt consume as many resources as if it was done continuosly).
* All the information that is exchanged between the application and the user will be securely stored in pods, thus increasing the privacy of the user.


==== Change Scenarios
The application is open to receive possible optional extensions that will increment the already existing funcionality or that will make the application offer different services.
Some of them were provided by the teachers of the subject:

* The application can offer other services to the users like notifications to users that are nearby, friend suggestions, geolocalized pictures or multimedia content published by friends, etc.
* It is possible to enrich the locations with comments, pictures, videos, etc.
* The system could get access to mobile information using bluetooth
* The web application can visualize maps with the locations made by one or more users
* It may be possible to offer other types of visualization about users' locations and their friends.
* It may be possible to tag locations to facilitate their search
* The application could send messages between nearby users so they get in touch
* It may be possible to notify positive COVID cases to facilitate tracking of people known with whom someone could have interacted

While we, as a team, thought about some other different extensions that could happen:

* The application can create a route from a set of different locations. This route may have a description stablishing what is its main appeal and the locations that should be visited.
* A planification feature, where you can stablish that you're going to visit a location today, so your friends can see that you are going and decide that they are going too and meet there.
* Ratings on each location, all the users can vote whether they like the location or not when they are nearby (one vote per person) so if the location is popular, it will be suggested more.
* A history feature for each profile (may be private or can be public to friends) in which all the visited locations are stored in a diary kind of way.
* A recommended feature for each profile, in which users may recommend specific locations to the users of the application
* An achievement system for the users to obtain. Visiting locations or using the application, the user may gain different titles or options to display in their profile.


Thus, the design of the application should be open to these changes while it is still completely functional without them.

