[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.
****

Qualities (esto hay que pasarlo a forma de dibujo):
_Efficiency_ - Fast comunications between the mobile and the web applications 
_Privacy_ - Information stored in pods
_Testability_ - Integrated server dedicated for tests
_Usability_ - Easy and simple to use user interface
_Connectivity?_ - Integration to receive notifications between the different users' device 

=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****

==== Usage Scenarios
* The aplication will be testeable since using the React framework will allow us to find bugs and possible errors easily, since tests will be run in a continuos integration server. 
* The application is also responsive: The Web application will record the locations just as the user will register them, and the mobile application will receive the notifications from nearby users as soon as the devices can.
* All the information that is exchanged between the application and the user will be stored in pods, increasing the privacy of the user.


==== Change Scenarios
The application is open to receive possible optional extensions that will increment the already existing funcionality or that will make the application offer different services.
Some of these optional features are:

* The application can offer other services to the users like notifications to users that are nearby, friend suggestions, geolocalized pictures or multimedia content published by friends, etc.
* It is possible to enrich the locations with comments, pictures, videos, etc.
* The system could get access to mobile information using bluetooth
* The web application can visualize maps with the locations made by one or more users
* It may be possible to offer other types of visualization about users' locations and their friends.
* It may be possible to tag locations to facilitate their search
* The application could send messages between nearby users so they get in touch
* It may be possible to notify positive COVID cases to facilitate tracking of people known with whom someone could have interacted

Thus, the design of the application should be open to these changes while it is still completely functional without them.

